### ISSUE TITLE
Post build runs for each nested object in builder

### ISSUE THREAD

**Issue by dylanpinn** [jackfranklin/test-data-bot#173]
At the moment `postBuild` is running for nested objects.

E.g. 

```js
// test.js
const { build } = require("@jackfranklin/test-data-bot");

const userBuilder = build("User", {
  fields: {
    name: "jack",
    details: {
      age: 21,
      hair: "long"
    }
  },
  postBuild: user => {
    console.log(user);
    return user;
  }
});

userBuilder();
```

```bash
> node test.js
{ age: 21, hair: 'long' }
{ name: 'jack', details: { age: 21, hair: 'long' } }
```

Is this the expected behaviour?

**Comment by jackfranklin** [comment]
Definitely not - it looks like #174 fixes this so this should be fixed soon. Thanks for the bug report 👍

**Comment by Dobby89** [comment]
@jackfranklin When will this be released? I'm running `1.1.0` and it's still an issue.
